- .github/workflows/dev_deploy.yml
> [ci] CI/CD 파이프라인 구축

- .github/workflows/dev_deploy.yml
> [ci] CI/CD 파이프라인 수정

- src/main/java/muit/backend/controller/CommentController.java
- src/main/java/muit/backend/controller/LostController.java
- src/main/java/muit/backend/controller/PostController.java
- src/main/java/muit/backend/controller/ReplyController.java
- src/main/java/muit/backend/converter/CommentConverter.java
- src/main/java/muit/backend/domain/entity/member/Comment.java
- src/main/java/muit/backend/domain/entity/member/Reply.java
- src/main/java/muit/backend/dto/commentDTO/CommentReplyRequestDTO.java
- src/main/java/muit/backend/dto/commentDTO/CommentReplyResponseDTO.java
- src/main/java/muit/backend/repository/CommentRepository.java
- src/main/java/muit/backend/repository/ReplyRepository.java
- src/main/java/muit/backend/service/CommentService.java
- src/main/java/muit/backend/service/CommentServiceImpl.java
- (대)댓글 등록, 삭제, 조회 구현
- 아직 jwt 토큰 없어서 request body에 memberId 받았습니다.
<br/>
- 좋아요 기능은 후순위라서 아직 구현하지 않았습니다.
- 토큰 구현되면 request body - memberId 삭제
- post 관련 api에 엔드포인트 잘못된 것들 수정 예정
- 익명1, 익명2 등 카운팅에 대해서는 회의 때 논의해보고 방향을 잡고싶어서 남겨두었습니다
> [feat] create comment/reply CRD

- src/main/resources/templates/exampleHtml.html
> [fix] 배포 오류 해결(template html create)

- build.gradle
- src/main/java/muit/backend/apiPayLoad/exception/ExceptionAdvice.java
- build.gradle에서 swaggerDoc version 2.0.2 -> 2.7.0으로 수정
> [fix] exception advise - swagger 오류 해결

- src/main/java/muit/backend/apiPayLoad/exception/ExceptionAdvice.java
- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/controller/TheatreController.java
- src/main/java/muit/backend/converter/TheatreConverter.java
- src/main/java/muit/backend/dto/theatreDTO/TheatreResponseDTO.java
- src/main/java/muit/backend/repository/MusicalRepository.java
- src/main/java/muit/backend/repository/TheatreRepository.java
- src/main/java/muit/backend/service/EventServiceImpl.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
- src/main/java/muit/backend/service/theatreService/TheatreService.java
- src/main/java/muit/backend/service/theatreService/TheatreServiceImpl.java
> [feat] 뮤지컬, 공연장 검색 기능

- src/main/java/muit/backend/apiPayLoad/code/status/ErrorStatus.java
- src/main/java/muit/backend/controller/AmateurTicketController.java
- src/main/java/muit/backend/converter/AmateurTicketConverter.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurShow.java
- src/main/java/muit/backend/dto/amateurTicketDTO/AmateurTicketRequestDTO.java
- src/main/java/muit/backend/dto/amateurTicketDTO/AmateurTicketResponseDTO.java
- src/main/java/muit/backend/repository/AmateurShowRepository.java
- src/main/java/muit/backend/service/AmateurTicketService.java
- src/main/java/muit/backend/service/AmateurTicketServiceImpl.java
- 어드민이 소극장 티켓 전체 조회하는 api
- 특정 소극장 티켓 조회하는 api
- 특정 소극장 티켓 수정하는 api
> [feat] 어드민의 소극장 티켓 관리 api 구현

- src/main/java/muit/backend/BackendApplication.java
- src/main/java/muit/backend/controller/postController/LostController.java
- src/main/java/muit/backend/controller/postController/PostController.java
- src/main/java/muit/backend/controller/postController/ReviewController.java
- src/main/java/muit/backend/converter/postConverter/LostConverter.java
- src/main/java/muit/backend/converter/postConverter/PostConverter.java
- src/main/java/muit/backend/converter/postConverter/ReviewConverter.java
- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/dto/postDTO/LostResponseDTO.java
- src/main/java/muit/backend/dto/postDTO/PostResponseDTO.java
- src/main/java/muit/backend/dto/postDTO/ReviewResponseDTO.java
- src/main/java/muit/backend/service/CommentServiceImpl.java
- 댓글 수 반환합니다.
- 이미지 파일 필수 아닌 것으로 수정했습니다.
> [feat] responseDTO에 commentCount 추가

- build.gradle
- src/main/java/muit/backend/config/InterparkConfig.java
- src/main/java/muit/backend/controller/AdminController.java
- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
인터파크에서 주간 랭킹 상위 10개 뮤지컬 이름 가져오는 API
<br/>
<br/>
> [feat] 인터파크 랭킹 정보 가져오는 API 개발

- src/main/java/muit/backend/controller/CommentController.java
- src/main/java/muit/backend/controller/ReplyController.java
- src/main/java/muit/backend/dto/commentDTO/CommentReplyRequestDTO.java
- src/main/java/muit/backend/service/CommentService.java
- src/main/java/muit/backend/service/CommentServiceImpl.java
- memberId를 dto에서 가져오는 방식에서 jwt 토큰 사용하는 것으로 바꿉니다.
> [refactor] jwt 토큰 방식 적용

- src/main/java/muit/backend/apiPayLoad/code/status/ErrorStatus.java
- src/main/java/muit/backend/controller/AmateurController.java
- src/main/java/muit/backend/controller/EmailController.java
- src/main/java/muit/backend/controller/MemberController.java
- src/main/java/muit/backend/converter/AmateurConverter.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurCasting.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurShow.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurStaff.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurSummary.java
- src/main/java/muit/backend/dto/amateurDTO/AmateurEnrollRequestDTO.java
- src/main/java/muit/backend/dto/amateurDTO/AmateurEnrollResponseDTO.java
- src/main/java/muit/backend/dto/amateurDTO/AmateurShowResponseDTO.java
- src/main/java/muit/backend/repository/AmateurShowRepository.java
- src/main/java/muit/backend/repository/amateurRepository/AmateurCastingRepository.java
- src/main/java/muit/backend/repository/amateurRepository/AmateurNoticeRepository.java
- src/main/java/muit/backend/repository/amateurRepository/AmateurStaffRepository.java
- src/main/java/muit/backend/repository/amateurRepository/AmateurSummaryRepository.java
- src/main/java/muit/backend/repository/amateurRepository/AmateurTicketRepository.java
- src/main/java/muit/backend/s3/FilePath.java
- src/main/java/muit/backend/s3/UuidFile.java
- src/main/java/muit/backend/service/MemberServiceImpl.java
- src/main/java/muit/backend/service/amateurService/AmateurShowService.java
- src/main/java/muit/backend/service/amateurService/AmateurShowServiceImpl.java
> [feat] 소극장 공연 생성, 조회, 리스트 조회 완성

- src/main/java/muit/backend/controller/EventController.java
- src/main/java/muit/backend/controller/adminController/ManageMusicalController.java
- src/main/java/muit/backend/service/EventService.java
- src/main/java/muit/backend/service/EventServiceImpl.java
> [feat] Event 관련 API 완성

- src/main/java/muit/backend/controller/postController/LostController.java
- src/main/java/muit/backend/controller/postController/PostController.java
- src/main/java/muit/backend/controller/postController/ReviewController.java
- src/main/java/muit/backend/converter/postConverter/LostConverter.java
- src/main/java/muit/backend/converter/postConverter/ReviewConverter.java
- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/repository/PostRepository.java
- src/main/java/muit/backend/service/postService/LostService.java
- src/main/java/muit/backend/service/postService/LostServiceImpl.java
- src/main/java/muit/backend/service/postService/PostService.java
- src/main/java/muit/backend/service/postService/PostServiceImpl.java
- src/main/java/muit/backend/service/postService/ReviewService.java
- src/main/java/muit/backend/service/postService/ReviewServiceImpl.java
> [feat] 검색 기능 추가

- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/controller/adminController/ManageMusicalController.java
- src/main/java/muit/backend/controller/adminController/ManageViewController.java
- src/main/java/muit/backend/converter/CastingConverter.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/domain/entity/musical/Casting.java
- src/main/java/muit/backend/domain/entity/musical/Musical.java
- src/main/java/muit/backend/dto/castingDTO/CastingResponseDTO.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/repository/ActorRepository.java
- src/main/java/muit/backend/repository/CastingRepository.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
1. 관리자 뮤지컬 관리 중 조회 부분
2. 뮤지컬 캐스팅정보 조회
뮤지컬 관리 조회 부분 응답에 맞게 와프 수정 필요
<br/>
<br/>
> [feat] 뮤지컬에서 캐스팅 정보 조회 API

- src/main/java/muit/backend/apiPayLoad/exception/ExceptionAdvice.java
- 기존에 에러 출력이 표준입출력이라 에러 레벨 설정이 안되어서 알림이 안왔습니다.
- 로깅 프레임워크 사용해 로그를 출력하도록 바꾸었습니다
- 코드 500 에러만 디스코드로 전송합니다
> fix : change error level

- src/main/java/muit/backend/domain/entity/member/Post.java
- patch 요청 시 이미지 수정 반영이 안되어서 로직 고쳤습니다
> fix : post patch logic for imageList changed

- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
> [feat] 오픈 예정 뮤지컬 보강

- src/main/java/muit/backend/controller/postController/LostController.java
- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/dto/postDTO/LostRequestDTO.java
- src/main/java/muit/backend/dto/postDTO/LostResponseDTO.java
- 분실물글 requestDTO 와 엔티티 타입 수정: lostDate type을 LocalDateTime 에서 LocalDate로
- QueryString 에서 lostDate 타입을 String에서 LocalDate로 변경
> [fix] LostRequestDTO changed

- src/main/java/muit/backend/apiPayLoad/code/status/ErrorStatus.java
- src/main/java/muit/backend/config/EmailConfig.java
- src/main/java/muit/backend/config/RedisConfig.java
- src/main/java/muit/backend/config/RedisUtil.java
- src/main/java/muit/backend/controller/EmailController.java
- src/main/java/muit/backend/controller/TicketController.java
- src/main/java/muit/backend/dto/ticketDTO/TicketRequestDTO.java
- src/main/java/muit/backend/service/memberService/EmailService.java
- src/main/java/muit/backend/service/ticketService/MemberTicketService.java
- src/main/java/muit/backend/service/ticketService/MemberTicketServiceImpl.java
> [fix] 티켓 예약 오류 수정

- src/main/java/muit/backend/domain/entity/member/Comment.java
- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/service/postService/PostServiceImpl.java
- 댓글-답장 관계에 cascade on delete 설정
> [fix] reply cascade on comment delete

- src/main/java/muit/backend/controller/InquiryController.java
- src/main/java/muit/backend/converter/InquiryConverter.java
- src/main/java/muit/backend/domain/entity/member/InquiryResponse.java
- src/main/java/muit/backend/domain/entity/member/Member.java
- src/main/java/muit/backend/dto/inquiryDTO/InquiryRequestDTO.java
- src/main/java/muit/backend/dto/inquiryDTO/InquiryResponseDTO.java
- src/main/java/muit/backend/repository/InquiryRepository.java
- src/main/java/muit/backend/repository/PostRepository.java
- src/main/java/muit/backend/service/InquiryService.java
- src/main/java/muit/backend/service/InquiryServiceImpl.java
- 문의 CRD API 작업했습니다
<br/>
- 기능 실험 안해봤습니다. 추후 fix예정
> [feat] 일반 회원 문의 기능 추가

- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/controller/TheatreController.java
- src/main/java/muit/backend/controller/adminController/ManageMusicalController.java
- src/main/java/muit/backend/converter/EventConverter.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/eventDTO/EventResponseDTO.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/repository/TheatreRepository.java
- src/main/java/muit/backend/service/EventServiceImpl.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
- src/main/java/muit/backend/service/theatreService/TheatreServiceImpl.java
검색어 없을 시 모든 항목 조회하도록 처리
<br/>
<br/>
> [feat] 검색기능 보강

- build.gradle
- src/main/java/muit/backend/controller/MemberController.java
- src/main/java/muit/backend/converter/MemberConverter.java
- src/main/java/muit/backend/dto/memberDTO/LoginAccessTokenResponse.java
- src/main/java/muit/backend/service/MemberService.java
- src/main/java/muit/backend/service/MemberServiceImpl.java
- src/main/java/muit/backend/service/memberService/socialLogin/AuthResponse.java
- src/main/java/muit/backend/service/memberService/socialLogin/GoogleAccessTokenRequest.java
- src/main/java/muit/backend/service/memberService/socialLogin/GoogleAccessTokenResponse.java
- src/main/java/muit/backend/service/memberService/socialLogin/GoogleAccountProfileResponse.java
- src/main/java/muit/backend/service/memberService/socialLogin/GoogleClient.java
- src/main/java/muit/backend/service/memberService/socialLogin/GoogleOauthService.java
- src/main/java/muit/backend/service/memberService/socialLogin/OauthController.java
- src/main/java/muit/backend/service/memberService/socialLogin/SocialConfig.java
- src/main/java/muit/backend/service/memberService/socialLogin/SocialLoginType.java
> feat : 구글 로그인 기능 완성

- src/main/java/muit/backend/repository/PostRepository.java
- src/main/java/muit/backend/service/CommentServiceImpl.java
- 인기 게시판에서 검색 반영 안되던 것 수정했습니다.
- 대댓글 갯수가 게시글 전체 댓글 개수로 반영되지 않는 문제 해결합니다.
> [fix] hot board search and comment count

- src/main/java/muit/backend/domain/entity/musical/Casting.java
- src/main/java/muit/backend/service/musicalService/KopisXmlParser.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
> [refactor] 줄 삭제

- src/main/java/muit/backend/converter/postConverter/ReviewConverter.java
- src/main/java/muit/backend/dto/postDTO/ReviewResponseDTO.java
- 리뷰 응답 DTO에 musical Name 필드 추가합니다.
> [modify] add musicalName field to reviewDTO

- src/main/java/muit/backend/converter/postConverter/ReviewConverter.java
- createdAt, updatedAt을 DTO에 만들어두고 실수로 builder에서 빼먹어서 null값으로 전송된 것 수정
> [fix] review DTO 필드 중 할당되지 않은 값 수정

- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/domain/entity/musical/Musical.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/repository/PostRepository.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
- 뮤지컬 평균 평점을 DTO에 추가
- 일단 musical service에서 post repository 참조하는 방식으로 했습니다
> [feat] add musical avg rating

- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/repository/MusicalRepository.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
오늘 오픈 뮤지컬 컨트롤러 추가
<br/>
<br/>
<br/>
> [feat] 오늘 오픈 뮤지컬 컨트롤러 추가

- src/main/java/muit/backend/controller/postController/CommonPostController.java
- src/main/java/muit/backend/controller/postController/LostController.java
- src/main/java/muit/backend/controller/postController/ReviewController.java
- src/main/java/muit/backend/converter/CommentConverter.java
- src/main/java/muit/backend/converter/postConverter/LostConverter.java
- src/main/java/muit/backend/converter/postConverter/PostConverter.java
- src/main/java/muit/backend/converter/postConverter/ReviewConverter.java
- src/main/java/muit/backend/domain/entity/member/Comment.java
- src/main/java/muit/backend/dto/postDTO/LostResponseDTO.java
- src/main/java/muit/backend/dto/postDTO/PostResponseDTO.java
- src/main/java/muit/backend/dto/postDTO/ReviewResponseDTO.java
- src/main/java/muit/backend/service/CommentServiceImpl.java
- src/main/java/muit/backend/service/postService/LostService.java
- src/main/java/muit/backend/service/postService/LostServiceImpl.java
- src/main/java/muit/backend/service/postService/PostServiceImpl.java
- src/main/java/muit/backend/service/postService/ReviewService.java
- src/main/java/muit/backend/service/postService/ReviewServiceImpl.java
- 게시글 삭제 가능 여부 + 관리자 게시글 삭제 기능 추가
> [feat] 게시글 삭제 가능 여부 + 관리자 게시글 삭제 기능

- src/main/java/muit/backend/apiPayLoad/code/status/ErrorStatus.java
- src/main/java/muit/backend/controller/EmailController.java
- src/main/java/muit/backend/controller/MemberController.java
- src/main/java/muit/backend/converter/AmateurConverter.java
- src/main/java/muit/backend/domain/entity/Admin.java
- src/main/java/muit/backend/domain/entity/amateur/AmateurShow.java
- src/main/java/muit/backend/domain/entity/member/Member.java
- src/main/java/muit/backend/dto/memberDTO/MyPageResponseDTO.java
- src/main/java/muit/backend/service/MemberService.java
- src/main/java/muit/backend/service/MemberServiceImpl.java
- src/main/java/muit/backend/service/memberService/socialLogin/OauthController.java
> fix : 소극장 공연, swagger 용 tag, 회원 탈퇴 구현

- src/main/java/muit/backend/domain/entity/musical/Event.java
event엔티티에서 eventType필드 제거
<br/>
<br/>
<br/>
> feat : eventType필드 제거

- src/main/java/muit/backend/converter/MemberTicketConverter.java
- src/main/java/muit/backend/domain/entity/member/MemberTicket.java
- src/main/java/muit/backend/dto/ticketDTO/TicketRequestDTO.java
- src/main/java/muit/backend/dto/ticketDTO/TicketResponseDTO.java
- src/main/java/muit/backend/s3/FilePath.java
- src/main/java/muit/backend/service/ticketService/MemberTicketServiceImpl.java
> [fix]: 티켓 예매에 accountName 추가

- src/main/java/muit/backend/service/memberService/socialLogin/OauthController.java
- src/main/java/muit/backend/service/memberService/socialLogin/kakao/KakaoAccessTokenResponse.java
- src/main/java/muit/backend/service/memberService/socialLogin/kakao/KakaoAccountProfileResponse.java
- src/main/java/muit/backend/service/memberService/socialLogin/kakao/KakaoClient.java
- src/main/java/muit/backend/service/memberService/socialLogin/kakao/KakaoOauthService.java
> feat: 카카오 로그인 구현

- src/main/java/muit/backend/domain/entity/member/Post.java
> [fix] yml 업데이트

- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/service/memberService/socialLogin/kakao/KakaoOauthService.java
> [merge] 250214 / 24th deploy

- src/main/java/muit/backend/service/MemberServiceImpl.java
> [fix] memberServiceImpl 오버라이드 해결

- src/main/java/muit/backend/controller/MusicalController.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/service/musicalService/MusicalService.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
뮤지컬 단건조회 dto에 isLike 필드추가
<br/>
<br/>
<br/>
> [feat] isLike 추가

- src/main/java/muit/backend/controller/EventController.java
- src/main/java/muit/backend/converter/EventConverter.java
- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/eventDTO/EventResponseDTO.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/service/EventService.java
- src/main/java/muit/backend/service/EventServiceImpl.java
- src/main/java/muit/backend/service/musicalService/MusicalServiceImpl.java
이벤트 조회시 isLike필드 추가
<br/>
<br/>
<br/>
> [feat] event 조회 보강 

- src/main/java/muit/backend/domain/entity/member/Post.java
- src/main/java/muit/backend/service/postService/PostServiceImpl.java
- 기존 이미지에 변경이 없어서 dto에 추가안해서 보낼 경우 로직 추가
> [fix] deals null imgArray on patch logic

- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
> [feat] 뮤지컬 단건조회 공연장 id 필드 추가

- src/main/java/muit/backend/converter/MusicalConverter.java
- src/main/java/muit/backend/dto/musicalDTO/MusicalResponseDTO.java
- src/main/java/muit/backend/service/MemberServiceImpl.java
> [merge] 250219 / 35th deploy

- src/main/java/muit/backend/controller/postController/LostController.java
- src/main/java/muit/backend/repository/PostRepository.java
- src/main/java/muit/backend/service/postService/LostServiceImpl.java
> [fix] fix lost date serach

- src/main/java/muit/backend/controller/adminController/ManageInquiryController.java
- src/main/java/muit/backend/converter/adminConverter/InquiryResponseConverter.java
- src/main/java/muit/backend/domain/entity/member/InquiryResponse.java
- src/main/java/muit/backend/repository/InquiryRepository.java
- src/main/java/muit/backend/service/InquiryServiceImpl.java
- src/main/java/muit/backend/service/adminService/InquiryResponseService.java
- src/main/java/muit/backend/service/adminService/InquiryResponseServiceImpl.java
- 상태 필터(AWAIT, COMPLETED) 가 적용이 안되어있어 적용시킴
- 어드민이 문의 답변 등록 시 어드민 id 포함하여 엔티티 생성
> [fix] inquiry get list + add response logic fixed

- src/main/java/muit/backend/controller/InquiryController.java
- src/main/java/muit/backend/repository/InquiryRepository.java
- src/main/java/muit/backend/service/InquiryService.java
- src/main/java/muit/backend/service/InquiryServiceImpl.java
> [modify] status filter delete

- src/main/java/muit/backend/controller/EventController.java
- src/main/java/muit/backend/repository/EventRepository.java
- src/main/java/muit/backend/service/EventService.java
- src/main/java/muit/backend/service/EventServiceImpl.java
> [feat] 이벤트 조회 종료날짜 기준으로 수정
